@startuml

!include <C4/C4_Container.puml>

System_Boundary("SmartHome", "Умный дом") {
    System_Boundary("DeviceDomain", "Домен: Умные устройства") {
        System(ManageDevice, "Контекст: Использование устройств", "Получение данных с устройств и изменение их состояния")
        System(RegisterDevice, "Контекст: Регистрация устройств", "Создание и управление заявками на выезд специалиста для установки устройства")
    }

    System_Boundary("UserDomain", "Домен: Пользователи") {
        System(ManageUser, "Контекст: Управление пользователями", "Регистрация новых пользователей, изменение данных по существующим пользователям")
    }
}
@enduml